export const country_detail_data = [

  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 616,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 137,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 731,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 404,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 896,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 910,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 638,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 736,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 316,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 947,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 797,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 389,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 956,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 342,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 847,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 974,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 707,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 91,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 587,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 960,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 447,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 588,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 515,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 774,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 442,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 327,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 377,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 16,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 360,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 785,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 356,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 393,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 995,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 207,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 186,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 73,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 717,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 551,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 994,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 641,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 689,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 89,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 852,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 178,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 56,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 565,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 675,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 300,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 70,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 921,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 809,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 911,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 467,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 157,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 364,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 793,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 232,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 43,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 504,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 332,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 605,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 110,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 194,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 436,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 478,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 54,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 548,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 983,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 982,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 180,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 747,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 258,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 17,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 945,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 70,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 790,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 377,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 72,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 262,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 996,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 481,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 727,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 557,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 129,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 786,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 905,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 102,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 297,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 934,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 666,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 409,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 590,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 901,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 557,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 440,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 957,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 256,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 836,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 534,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 125,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 87,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 120,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 124,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 321,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 204,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 266,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 261,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 647,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 916,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 126,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 470,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 471,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 584,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 992,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 770,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 881,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 997,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 27,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 332,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 674,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 476,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 850,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 25,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 995,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 230,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 910,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 974,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 910,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 939,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 689,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 166,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 14,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 664,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 147,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 226,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 498,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 949,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 897,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 451,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 974,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 840,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 680,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 909,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 677,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 45,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 952,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 242,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 179,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 346,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 409,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 674,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 470,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 219,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 738,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 388,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 562,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 722,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 432,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 369,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 696,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 456,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 208,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 971,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 386,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 838,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 788,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 89,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 825,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 767,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 417,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 11,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 702,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 815,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 488,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 252,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 896,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 484,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 14,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 368,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 576,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 714,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 9,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 150,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 481,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 406,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 625,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 230,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 163,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 291,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 683,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 913,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 965,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 768,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 87,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 621,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 577,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 126,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 142,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 363,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 849,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 704,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 891,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 167,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 381,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 768,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 995,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 188,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 265,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 1000,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 999,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 914,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 917,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 705,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 338,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 561,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 803,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 531,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 429,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 143,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 126,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 642,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 950,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 283,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 969,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 933,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 930,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 199,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 525,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 613,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 713,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 150,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 576,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 732,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 778,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 739,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 870,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 944,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 398,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 436,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 428,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 175,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 955,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 815,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 9,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 86,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 455,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 581,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 962,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 260,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 679,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 914,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 534,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 534,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 193,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 80,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 187,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 596,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 112,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 499,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 883,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 655,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 213,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 928,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 405,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 904,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 148,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 954,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 400,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 843,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 606,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 727,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 798,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 815,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 864,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 685,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 679,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 430,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 374,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 198,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 133,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 621,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 634,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 903,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 691,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 21,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 65,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 594,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 640,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 558,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 862,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 850,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 468,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 31,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 963,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 873,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 678,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 191,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 915,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 420,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 786,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 549,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 974,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 148,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 201,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 648,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 821,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 558,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 462,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 344,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 500,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 84,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 952,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 37,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 851,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 129,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 915,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 716,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 486,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 332,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 511,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 724,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 509,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 238,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 6,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 782,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 925,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 568,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 696,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 73,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 465,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 43,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 662,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 350,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 782,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 650,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 702,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 71,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 981,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 536,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 602,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 170,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 134,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 53,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 258,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 223,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 311,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 764,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 70,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 276,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 386,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 505,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 426,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 430,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 203,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 475,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 170,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 474,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 846,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 847,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 386,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 206,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 271,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 979,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 499,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 56,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 993,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 802,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 791,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 559,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 92,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 618,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 900,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 98,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 212,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 54,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 602,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 717,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 608,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 864,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 183,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 11,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 887,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 476,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 825,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 851,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 250,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 907,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 633,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 460,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 695,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 410,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 422,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 874,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 4,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 773,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 522,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 42,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 907,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 699,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 69,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 297,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 501,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 641,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 8,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 994,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 215,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 887,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 821,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 996,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 428,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 424,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 823,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 780,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 954,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 406,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 82,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 928,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 486,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 180,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 471,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 583,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 237,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 276,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 618,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 149,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 831,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 287,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 465,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 496,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 830,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 247,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 50,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 940,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 71,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 171,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 530,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 559,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 843,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 467,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 721,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 162,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 859,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 406,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 624,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 913,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 913,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 836,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 770,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 383,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 999,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 440,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 399,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 876,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 685,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 499,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "ODS",
    star_count: 20,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 991,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 474,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 505,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 88,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 193,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 665,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 974,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 224,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 590,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 437,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "VS",
    star_count: 443,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 10,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 614,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 869,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 686,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "OAS",
    star_count: 609,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 514,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 856,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 533,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Malicious Flow",
    attack_category: "MAS",
    star_count: 732,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Malicious Flow",
    attack_category: "IDS",
    star_count: 64,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "MAS",
    star_count: 199,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "Median",
    flow_category: "Malicious Flow",
    attack_category: "OAS",
    star_count: 721,
    data_set: [5, 8, 2, 8, 5, 4, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 890,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "VS",
    star_count: 462,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
  {
    serverity: "High",
    flow_category: "Total Flow",
    attack_category: "ODS",
    star_count: 951,
    data_set: [5, 7, 10, 8, 8, 2, 5, 8, 1, 2],
  },
  {
    serverity: "Low",
    flow_category: "Total Flow",
    attack_category: "IDS",
    star_count: 518,
    data_set: [1, 4, 5, 6, 7, 8, 9, 8, 1, 2],
  },
]
    export default country_detail_data;